### ISSUE TITLE
update for IAM token

### ISSUE THREAD

**Issue by scottdangelo** [IBM/predictive-model-on-watson-ml#20]
IAM token has replaced the Cloud Foundry uname and password. The notebook and docs need to be changed to reflect this.

**Comment by timroster** [comment]
Tested notebook with instance of WML from 7/29 and found it includes apikey and also username:password. The Watson ML SDK `https://watson-ml-libs.mybluemix.net/repository-python/index.html` still uses username:password. This doesn't look like an issue to fix yet.

**Comment by stevemart** [comment]
see #35 for this issue

**Comment by stevemar** [comment]
the Watson ML SDK is Just starting to roll this out. The python and javascript used in the app and tester still use username and password, the notebook does NOT.

**Comment by stevemar** [comment]
this has been updated for some time.
