### ISSUE TITLE
Handle automatic model builder deployment

### ISSUE THREAD

**Issue by justinmccoy** [IBM/predictive-model-on-watson-ml#22]
The deployed app doesn't handle models built from the Automatic Model Builder and from the iPython Notebook, update the app to handle both cases.

**Comment by stevemar** [comment]
The instructions are here: https://github.com/justinmccoy/lab-watson-automatic-model-builder

I'll take a whack at merging these instructions into the README

**Comment by stevemar** [comment]
the proposed refresh will use AutoAI, the precursor to model builder, so this will happen. See branch https://github.com/IBM/predictive-model-on-watson-ml/tree/refresh-pattern
