### ISSUE TITLE
Cannot connect ML instance to running app

### ISSUE THREAD

**Issue by scottdangelo** [IBM/predictive-model-on-watson-ml#29]
I do not believe that this is an issue with this code pattern. It is likely a cloud infrastructure issue, but I am documenting here.

When attempting to use the Machine Learning connection tab to connect to the deployed app, which is in `Dev Advocacy/dev` and `Dallas`:

![image](https://user-images.githubusercontent.com/14651388/50158731-2b830b80-0292-11e9-88e2-74d500a83d0f.png)

This fails, with `no compatible app found` : 

![image](https://user-images.githubusercontent.com/14651388/50158888-89175800-0292-11e9-96c7-981e7a6239b9.png)

When attempting to use the Cloud app connection tab to connect an existing compatible service, the ML service shows up:

![image](https://user-images.githubusercontent.com/14651388/50158464-6cc6eb80-0291-11e9-8df9-5539f3d9c258.png)

But when the `Connect` button is clicked, there is an error `Failed to get service plan`: 

![image](https://user-images.githubusercontent.com/14651388/50158512-89632380-0291-11e9-84f5-33312a53a515.png)

**Comment by scottdangelo** [comment]
It looks like the issue is that the app is in `Default` and the ML is in `Developer Advocacy`.

**Comment by scottdangelo** [comment]
Note that the IAM key is created and the choices are `Developer Advocacy` and `dev` : 

![image](https://user-images.githubusercontent.com/14651388/50159260-82d5ab80-0293-11e9-8be3-14cc122938ee.png)

**Comment by scottdangelo** [comment]
Here's the deployment to `Developer Advocacy` and `dev` : 

![image](https://user-images.githubusercontent.com/14651388/50159351-b87a9480-0293-11e9-9680-3621c3de3b9c.png)

**Comment by spackows** [comment]
Hi, again.

I am not able to reproduce your problem..

<p>&nbsp;</p>

## Steps I followed

1.  I have a Node.js app running with hard-coded WML credentials.  When I go to the details page for that Node.js app. I see the option to create a connection:
![image](https://user-images.githubusercontent.com/18294329/50240698-6c167e00-0393-11e9-94a3-e88187aba977.png)

2.  When I click **Create connection**, I see a WML instance in the list:
![image](https://user-images.githubusercontent.com/18294329/50240733-949e7800-0393-11e9-9f55-b50998370e28.png)
(It has ais in the name, but it's actually plain, old WML.)

3.  When I click **Connect**, I see the modal:
![image](https://user-images.githubusercontent.com/18294329/50240764-a97b0b80-0393-11e9-958d-cf49f6c7f921.png)

4. When I click **Connect**, it just works:
![image](https://user-images.githubusercontent.com/18294329/50240789-b992eb00-0393-11e9-9b95-af6046eba8bf.png)

5.  When I update my Node.js app to use VCAP_SERVICES for credentials, that works too.

<p>&nbsp;</p>


## Resource Group vs Org??

I should say too that my WML instance is in the "Default" Resource Group:
![image](https://user-images.githubusercontent.com/18294329/50240986-4e95e400-0394-11e9-82e0-5395697f3414.png)

And my Node.js app is in my (non-IBM, external) Org, "mlcli(at)maharaj.ca":
![image](https://user-images.githubusercontent.com/18294329/50241023-640b0e00-0394-11e9-8d1a-106cf56bf981.png)

<p>&nbsp;</p>

I don't know if that was helpful.. Except that this outcome makes me think there is NOT a widespread general problem with connecting WML to apps.

**Comment by scottdangelo** [comment]
Thanks for attempting to reproduce the issue. This is helpful information.
I'll keep looking at other angles.

**Comment by stevemar** [comment]
This is an issue with orgs, regions and spaces. Try to keep the app and the WML service in the same org/space/region
