### ISSUE TITLE
Testing Application returns 503 error

### ISSUE THREAD

**Issue by scottdangelo** [IBM/predictive-model-on-watson-ml#8]
The ML model is build and works inside the Notebook using the APIs. The ML dashboard shows:
Deployment Type | online
Deployment Status | ACTIVE

The app is connected to the ML service.
But when I try to `Score` in the app GUI, I get the following:

<img width="907" alt="guierror503" src="https://user-images.githubusercontent.com/14651388/35828739-e15c7b16-0a7d-11e8-949f-38fbcdb0298b.png">

and the server app logs show:

<img width="664" alt="errorlog" src="https://user-images.githubusercontent.com/14651388/35828761-eede6826-0a7d-11e8-8454-f8c8d3666378.png">

**Comment by justinmccoy** [comment]
Restart the NodeJS app after deploying the model.

**Comment by scottdangelo** [comment]
Fixed. Sorry, thought I had done that.
